name: Build a deb package

on:
  push:
    paths:
      - '.kpxc-upstream-version'
  workflow_dispatch: # on button click

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0
      - name: Checkout latest release tag
        run: |
          LATEST_TAG=$(git describe --tags `git rev-list --tags --max-count=1`)
          echo "Latest tag is $LATEST_TAG"
          git checkout tags/$LATEST_TAG
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: -i -us -uc -b
      - name: List files
        run: ls -R
