on:
  push:
    paths:
      - '.kpxc-upstream-version'
  workflow_dispatch: # on button click

jobs:
  build-debs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: jtdor/build-deb-action@v1
        env:
          DEB_BUILD_OPTIONS: noautodbgsym
        with:
          buildpackage-opts: -i -us -uc -b
