name: Get latest release version
on:
  schedule:
    - cron:  '0 10 * * *'
  workflow_dispatch: # on button click
jobs:
  get-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Fetch release version
        run: |
          curl -sL https://api.github.com/repos/keepassxreboot/keepassxc/releases/latest | \
          jq -r ".tag_name" > release-versions/keepassxc-latest.txt
      - name: Check for modified files
        id: git-check
        run: echo ::set-output name=modified::$([ -z "`git status --porcelain`" ] && echo "false" || echo "true")
      - name: Commit latest release version
        if: steps.git-check.outputs.modified == 'true'
        run: |
          git config --global user.name 'Release Bot'
          git config --global user.email 'release-bot@users.noreply.github.com'
          git commit -am "Found new release version $(cat release-versions/keepassxc-latest.txt)"
          git remote add upstream https://github.com/keepassxreboot/keepassxc.git
          git fetch --tags upstream
          sed -i "1s/^/keepassxc ($(cat release-versions/keepassxc-latest.txt)-1~jammy1) jammy; urgency=medium\n\n  * Upstream update\n\n -- Fabian Schillig <xorgmc@gmail.com>  $(date -R)\n\n/" debian/changelog
          git merge --no-edit tags/$(cat release-versions/keepassxc-latest.txt)
          git push
